/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PrestacoesProduto;


import java.util.Scanner;

public class App {
    

    public static void main(String[] args) {
        
        
    /*A Loja Mamão com Açúcar está vendendo seus produtos em5(cinco)prestações sem juros. Faça um 
    algoritmo que receba um valor de uma compra e mostre o valor das prestações;*/
    
    
        float valorCompra = 0;
        float prestacoes = 0;
        int opcao = 0;
        
        Scanner leitor = new Scanner(System.in);
        
        System.out.println("Valor da compra: R$ ");
        valorCompra = leitor.nextFloat();
        
        System.out.println("Ate 5x sem juros ou mais vezes com juros de 0.08%");
        System.out.println("Escolha as opcoes abaixo:");
        
        System.out.println("Opcao 1 - [ 1x a vista ]");
        System.out.println("Opcao 2 - [ 2x sem juros ]");
        System.out.println("Opcao 3 - [ 3x sem juros ]");
        System.out.println("Opcao 4 - [ 4x sem juros ]");
        System.out.println("Opcao 5 - [ 5x sem juros ]");
        System.out.println("Opcao 6 - [ 6x com juros ]");
        System.out.println("Opcao 7 - [ 7x com juros ]");
        System.out.println("Opcao 8 - [ 8x com juros ]");
        System.out.println("Opcao 9 - [ 9x com juros ]");
        System.out.println("Opcao 10 - [ 10x com juros ]");
        
        System.out.println("Digite a opcao: ");
        opcao = leitor.nextInt();
        
        switch (opcao) {
            case 1:
                System.out.println("Voce escolheu 1x a vista");
                break;
            case 2:
                valorCompra = valorCompra / 2;
                System.out.println("Voce escolheu 2x sem juros de R$ " + valorCompra);
                break;
            case 3:
                valorCompra = valorCompra /3;
                System.out.println("Voce escolheu 3x sem juros de R$ " + valorCompra);
                break;
            case 4:
                valorCompra = valorCompra /4;
                System.out.println("Voce escolheu 4x sem juros de R$ " + valorCompra);
                break;
            case 5:
                valorCompra = valorCompra /5;
                System.out.println("Voce escolheu 5x sem juros de R$ " + valorCompra);
                break;
            case 6:
                valorCompra = (valorCompra * 0.08f + valorCompra) / 6;
                System.out.format("Voce escolheu 6x com juros de R$ " + "%.2f", valorCompra);
                break;
            default:
                break;
        }
    }
}
